schema:
  - 'http://127.0.0.1:5000/graphql':
      headers:
        Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5NjQxNzA5OCwianRpIjoiYjczMTY4YzYtNmRlYy00NjJjLWE1ZTUtYmE3NDI1MjI5OWFhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Ijc0YjEyMTY0LWM4ZjktNDRjZS04ZjY1LWNlOTIwNmFmODhhYyIsIm5iZiI6MTY5NjQxNzA5OCwiZXhwIjoxNjk3MDIxODk4fQ.hbVES3bAs6Jv1R6ieTX9c_rjWsUix_eCuq0Hi2ssW4o'
documents: 'src/**/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
