schema:
  - 'http://127.0.0.1:5000/graphql':
      headers:
        Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY5NjU4OTAwNiwianRpIjoiNTU5ZGIzOTUtZWYyOC00MzUwLWFiM2EtODc1YjVhNTZkMDhhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjA2MzMyMmNlLTAwOTAtNDJkZi1iOThlLWUwZDAwNWQyM2FhMiIsIm5iZiI6MTY5NjU4OTAwNiwiZXhwIjoxNjk3MTkzODA2fQ.6LmM_lwGfndHX-AP6kY4StcXaTMRnJWwrEIPw1-33h8'
documents: 'src/**/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
