version: '3.1'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  backend:
    build: backend
    ports:
      - "5005:5005"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_REGION=us-west-2
    depends_on:
      - dynamodb-local

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
